"""Optimization_details

Revision ID: 51263c34ebdd
Revises:
Create Date: 2025-07-07 19:25:54.355315

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "51263c34ebdd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('emulator_log', sa.Column('optimization_details', sa.JSON(), nullable=True))
    # op.alter_column('emulator_log', 'status',
    #            existing_type=sa.VARCHAR(length=7),
    #            type_=sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='runstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('emulator_log', 'status',
    #            existing_type=sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='runstatus'),
    #            type_=sa.VARCHAR(length=7),
    #            existing_nullable=False)
    # op.drop_column('emulator_log', 'optimization_details')
    # ### end Alembic commands ###
